spring:
  application:
    name: api1
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.ccmkllzeb6nw.ap-northeast-2.rds.amazonaws.com:3306/springdb
    username: springdbuser
    password: springdbuser

    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
